name: Build & Release Extensions

on:
  workflow_dispatch:

jobs:
  release:
    name: Build & Release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Build all extensions
        run: npm run build

      - name: Zip Chrome extension
        run: |
          cd packages/chrome/dist
          zip -r ../../chrome-extension.zip .
          cd ../../..

      - name: Zip Firefox extension
        run: |
          cd packages/firefox/dist
          zip -r ../../firefox-extension.zip .
          cd ../../..

      - name: Upload Chrome extension artifact
        uses: actions/upload-artifact@v4
        with:
          name: chrome-extension
          path: packages/chrome-extension.zip

      - name: Upload Firefox extension artifact
        uses: actions/upload-artifact@v4
        with:
          name: firefox-extension
          path: packages/firefox-extension.zip

      - name: Create Release (semantic-release)
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
